[package]
name = "aliens-vs-suburbia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_rand = "0.4.0"
bevy_xpbd_3d = { version = "0.3.2", default-features = false, features = ["3d", "f32", "debug-plugin", "collider-from-mesh", "async-collider", "simd", "parallel"] }
big-brain = { git="https://github.com/zkat/big-brain", branch="main" }
rand_chacha = "0.3.1"
flagset = "0.4.4"
serde = "1.0.193"
serde_json = "1.0.108"
pathfinding = "4.6.0"
itertools = "0.12.0"
belly = { git="https://github.com/jkb0o/belly/", branch="0.12" }
bevy_mod_outline = "0.6.0"
bevy_video_glitch = "0.1.1"
bevy-inspector-egui = "0.22.0"
bevy_atmosphere = "0.8.1"
rand = "0.8.5"
image = "0.24.8"
noise = "0.8.2"
nalgebra = "0.32.3"
bitintr = "0.3.0"
palette = "0.7.3"
# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
