[package]
name = "aliens-vs-suburbia"
version = "0.1.0"
edition = "2021"

[features]
default = []
editor = ["space_editor/editor"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_gilrs",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi-threaded",
    "png",
    "hdr",
    "x11",
    "bevy_gizmos",
    "tonemapping_luts",
    "default_font",
    "webgl2",
    "bevy_debug_stepping",
] }
bevy_rand = "0.5.2"
bevy_xpbd_3d = { version = "0.4.2", default-features = false, features = ["3d", "f32", "debug-plugin", "collider-from-mesh", "async-collider", "parallel", "parry-f32", "default-collider", "enhanced-determinism"] }
big-brain = { git="https://github.com/zkat/big-brain.git", branch="main" }
rand_chacha = "0.3.1"
flagset = "0.4.5"
serde = "1.0.197"
serde_json = "1.0.114"
pathfinding = "4.9.1"
itertools = "0.12.1"
bevy_mod_outline = "0.6.2"
bevy_video_glitch = "0.1.1"
bevy-inspector-egui = "0.23.4"
bevy_atmosphere = "0.9.0"
rand = "0.8.5"
image = "0.25.0"
noise = "0.8.2"
nalgebra = "0.32.4"
bitintr = "0.3.0"
palette = "0.7.5"
space_editor = { git = "https://github.com/rewin123/space_editor.git", branch = "main" }
bevy_panorbit_camera = "0.16.1"
bevy_hanabi = "0.10.0"
rusty_music = { git = "https://github.com/lavaeater/rusty_music.git", branch = "main" }
# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
